<?php /** @var $block Magento\Theme\Block\Html\Footer */ ?>
<div id="back-top">
	<i title="<?php echo __('Back to Top'); ?>"></i>
	<a href="#"><?php echo __('Back to Top'); ?></a>
</div>
<small class="copyright">
    <span><?php echo $block->escapeHtml($block->getCopyright()) ?></span>
</small>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "footer": {
                           "component": "js/view/footer"
                        }
                }
            },
            "EloomLazyWidget": ""
        }
    }
</script>