<?php
/** @var $block \Eloom\ThemeFrontend\Block\Navigation\FilterRenderer */

if ($filter instanceof Magento\CatalogSearch\Model\Layer\Filter\Price):?>
	<?php
	$range = $this->getPriceRange($filter);
	$url = $this->getFilterUrl($filter);
	?>
	<script type="text/javascript">
		var priceUrl = "<?php echo $url;?>";
		require([
			'jquery',
			'priceUtils',
			"jquery/ui",
			'domReady!'
		], function ($, utils) {
			updateLabel = function () {
				var priceFormat = <?php echo $this->helper('Magento\Tax\Helper\Data')->getPriceFormat($block->getStore()); ?>;
				var min = utils.formatPrice($("#price-slider").slider("values", 0), priceFormat);
				var max = utils.formatPrice($("#price-slider").slider("values", 1), priceFormat);
				$("#amount").val(min + " - " + max);
			};
			$("div#price-slider").slider({
				range: true,
				min: <?=$range['min']?>,
				max: <?=$range['max']?>,
				values: [<?=$range['min']?>, <?=$range['max']?>],
				slide: function (event, ui) {
					updateLabel();
				},
				change: function (event, ui) {
					window.location.href = priceUrl.replace("price=", "price=" + ui.values[0] + "-" + ui.values[1]);
				}
			});
			updateLabel();
		});
	</script>

	<p>
		<label for="amount"><?= __('Price range:') ?></label>
		<input type="text" id="amount" readonly>
	</p>
	<div id="price-slider"></div>

<?php else: ?>
	<ol class="items">
		<?php foreach ($filterItems as $filterItem): ?>
			<li class="my item">
				<?php if ($filterItem->getCount() > 0): ?>
					<a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
						<?php echo $filterItem->getLabel() ?>
						<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
							<span class="count"><?php echo $filterItem->getCount() ?>
								<span class="filter-count-label"><?php if ($filterItem->getCount() == 1): ?><?php echo __('item') ?><?php else: ?><?php echo __('items') ?><?php endif; ?></span>
							</span>
						<?php endif; ?>
					</a>
				<?php else: ?>
					<?php echo $filterItem->getLabel() ?>
					<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
						<span class="count"><?php echo $filterItem->getCount() ?>
							<span class="filter-count-label"><?php if ($filterItem->getCount() == 1): ?><?php echo __('item') ?><?php else: ?><?php echo __('items') ?><?php endif; ?></span>
						</span>
					<?php endif; ?>
				<?php endif; ?>
			</li>
		<?php endforeach ?>
	</ol>
<?php endif; ?>
